version: '3.8'
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=CreditConveyor
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5433"
    restart: always