version: '3.8'
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Neoflex
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5433"
    restart: always