spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/CreditConveyor
    username: postgres
    password: root
  kafka:
    bootstrap-servers: localhost:9092


  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8081

conveyor:
  url: http://${CONVEYOR_URL:localhost}:8080/
