spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/CreditConveyor
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8081

conveyor:
  url: http://localhost:8080
